### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [pablopunk/chronocube#4]
i've downloaded version 0.5.1 but when selecting it in the Finder and using 'Get Info' it shows 'Version 0.30.1'

**Comment by pablopunk** [comment]
@core-code thanks, I've pushed a fix and will update the release files soon

**Comment by core-code** [comment]
awesome, thanks

**Comment by pablopunk** [comment]
@core-code I'm having a lot of trouble building the app. My makefile uses old modules that are very different now and I'm not maintaining this repo anymore. I (or any volunteer) should create a completely new electron app and copy this source there, because now building/packaging it's pretty easy and this repo is kind of messed up.
